params:
  epochs: 1
  batch_size: 32
  no_classes: 10
  input_shape: [28,28]
  LOSS_FUNCTION: sparse_categorical_crossentropy
  METRICS: accuracy
  OPTIMIZER: sgd
  validation_datasize: 5000
  patience: 5 
  restore_best_weights: True


artifacts:
  artifacts_dir: artifacts
  model_dir: model
  plots_dr: plots
  CHECKPOINTS_DIR: checkpoints
  model_name: model.h5
  plot_name: plots
  
  


  logs:
  logs_dir: logs_dir
  general_logs: general_logs
  TENSORBOARD_ROOT_LOG_DIR : tensorboard_log_dir 